on:
  workflow_dispatch:
  workflow_run:
    workflows: CI
    types:
      - completed
    branches:
      - main

name: Deploy to Oracle Cloud

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main') || github.event_name == 'workflow_dispatch' }}
    environment: OCI
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_PRIVATE_KEY }}
          script: |
            export PATH=/home/ubuntu/n/bin:/home/ubuntu/.bun/bin:$PATH
            cd hogwarts-productivity-hub-bot && 
            git pull &&
            pnpm install &&
            pnpm typecheck &&
            pnpm register &&
            npx drizzle-kit migrate &&
            systemctl --user restart hogwarts-bot.service &&
            curl -k -X POST https://localhost:3000/api/annotations \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ secrets.OCI_GRAFANA_API_KEY }}" \
              -d '{"text": "Deployment \"${{ github.event.workflow_run.head_commit.message }}\"", "tags": ["deploy", "hogwarts-bot"]}'
